openapi: 3.0.0
info:
  title: Swagger URL Shortener
  description: URL Shortener API
  termsOfService: http://swagger.io/terms/
  contact:
    email: admin@urlshortener.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /
tags:
- name: shortener
  externalDocs:
    description: Find out more
    url: http://urlshortener.com/doc
paths:
  /:
    post:
      tags:
      - shortener
      summary: Create new short link and add it to the store
      description: Creates new short link and returns it
      operationId: createShortLink
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LongLinkRequest'
        required: true
      responses:
        "201":
          description: successful created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLinkResponse'
        default:
          description: Some error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /{shortLink}:
    get:
      tags:
      - shortener
      summary: Get long link by short link
      description: Returns long link
      operationId: getLongLink
      parameters:
      - name: shortLink
        in: path
        description: Short link
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Link'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LongLinkResponse'
        default:
          description: Some error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    Link:
      type: string
    LongLinkResponse:
      type: object
      properties:
        longLink:
          $ref: '#/components/schemas/Link'
      example:
        longLink: longLink
    LongLinkRequest:
      type: object
      properties:
        longLink:
          $ref: '#/components/schemas/Link'
    ShortLinkResponse:
      type: object
      properties:
        shortLink:
          $ref: '#/components/schemas/Link'
      example:
        shortLink: shortLink
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
        error:
          type: string
